FROM python:3.12
WORKDIR /app
COPY requirements requirements
RUN pip install -r requirements/base.txt -r requirements/test.txt
COPY tablecache tablecache
COPY tests tests
COPY pyproject.toml setup.py .
