# Copyright 2024 Marc Lehmann

# This file is part of tablecache.
#
# tablecache is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# tablecache is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with tablecache. If not, see <https://www.gnu.org/licenses/>.

import asyncio
import datetime
import numbers
import typing as t

import asyncpg

import tablecache as tc
import tablecache.postgres as tcpg
import tablecache.local as tcl

# TODO add update functionality, i.e. regularly expire old ones and load ones
# TODO also let the indexes covers() cheat a bit by returning True for stuff up
# to a minute into the future
# TODO review all comments+++++++++++
# TODO demonstrate invalidations with changing scores, i.e. a call to
# invalidate_records where old_specs!=new_specs, and where we have multiple specs+++++++++++++
# TODO explain that for invalidation, the indexes must cover what's being invalidated+++++++
# TODO explain invalidation dirtying indexes++++++++++++++++

# In this example, we have a table of timestamped device data, and we want to
# be able to quickly query data from a time range (there is no joining going on
# here to simplify the demo, but a join of multiple relations would work just
# as well). Additionally, we only want to load the most recent data into the
# cache (as older data is rarely interesting). Older data can still be queried,
# but will hit Postgres rather than Redis.
#
# The Redis backend requires that each record has exactly one (float) score
# that defines its order by which it can be efficiently found. We will create a
# custom CachedSubset subclass that uses the timestamp as the score.

POSTGRES_DSN = 'postgres://postgres:@localhost:5432/postgres'


async def main():
    query_string = 'SELECT * FROM device_data WHERE ts >= $1 AND ts < $2'
    # The query_subset_string needs to have parameters $1 etc. that match the
    # parameters of our custom subset. In our case, we want to filter by
    # timestamp lower and upper bounds. Note that lower bounds are always
    # inclusive and upper bounds exclusive.
    indexes = TimeRangeIndexes('data_id', 'ts', query_string)
    db_access = tcpg.PostgresAccess(dsn=POSTGRES_DSN)
    storage_table = LocalStorageTable(indexes)
    table = tc.CachedTable(indexes, db_access, storage_table)
    async with db_access, asyncpg.create_pool(POSTGRES_DSN) as postgres_pool:
        await setup_example_db(postgres_pool)
        # TODO also demonstrate records being fetched from db that don't exist
        # in cache++++++++++
        # TODO and use record_parser=dict in the db access to more easily
        # distinguish between records from storage and db++++++++++++++
        # We're loading the table and specifying that records in the range from
        # 2023-01-01T12:00:00 to 2023-01-03T12:00:00 should be loaded (so there
        # are records before and after this range that aren't going into the
        # cache).
        await table.load('time', '2023-01-01T12:00:00', '2023-01-03T12:00:00')
        # Now that the cache is loaded, we can query it by subset. Depending on
        # whether the subset we query for is contained in the cache, we'll
        # either get all records from cache, or all from the DB. There is
        # currently no middle ground. If the subset is not fully cached, the DB
        # will be hit for everything.
        print('All records in cache:')
        await print_records('time', '2023-01-02', '2023-01-03')
        print('Not all records in cache (will be loaded from DB):')
        await print_records('time', '2023-01-01', '2023-01-05')
        # We can adjust the subset of records that should be cached. This will
        # cause old records to be discarded and new ones to be loaded.
        # Arguments are passed through to our subset's adjust() method. It is
        # up to the subset to decide which records are discarded and added.
        await table.adjust('time', '2023-01-03', '2023-01-05')
        print('Records we have expired from cache are loaded from the DB:')
        await print_records('time', '2023-01-02', '2023-01-03')
        print('Newer records were added to the cache:')
        await print_records('time', '2023-01-04', '2023-01-05')


async def setup_example_db(postgres_pool):
    await postgres_pool.execute(
        '''
        DROP SCHEMA public CASCADE;
        CREATE SCHEMA public;
        CREATE TABLE device_data (
            data_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            data integer NOT NULL,
            ts timestamp without time zone NOT NULL
        );

        INSERT INTO device_data(data, ts) VALUES
            (1, '2023-01-01T00:00:00Z'),
            (2, '2023-01-02T00:00:00Z'),
            (3, '2023-01-03T00:00:00Z'),
            (4, '2023-01-04T00:00:00Z');''')


async def print_records(table, *args, **kwargs):
    async for record in table.get_records(*args, **kwargs):
        print(record)

# TODO explain this+++++++++++++


class TimeRangeIndexes(tc.Indexes[numbers.Real]):
    class IndexSpec(tc.Indexes[tc.PrimaryKey].IndexSpec):
        def __init__(
                self, index_name: str, ge_isoformat: str, lt_isoformat: str):
            if index_name != 'time':
                raise ValueError('Only the time index exists.')
            super().__init__(index_name)
            self.ge = datetime.datetime.fromisoformat(ge_isoformat)
            self.lt = datetime.datetime.fromisoformat(lt_isoformat)
            if self.ge > self.lt:
                raise ValueError('Bounds are not in order.')

        def __repr__(self):
            return (
                f'IndexSpec specifying all records between {self.ge} and '
                f'{self.lt}')

    class Adjustment(tc.Adjustment):
        def __init__(
                self, expire_spec: t.Optional[tc.StorageRecordsSpec],
                load_spec: t.Optional[tc.DbRecordsSpec],
                ge: datetime.datetime, lt: datetime.datetime) -> None:
            super().__init__(expire_spec, load_spec)
            self.ge = ge
            self.lt = lt

    def __init__(
            self, primary_key_name: str, ts_attr_name: str,
            query_range_string: str) -> None:
        self._primary_key_name = primary_key_name
        self._ts_attr_name = ts_attr_name
        self._query_range_string = query_range_string
        self._ge = datetime.datetime.fromtimestamp(0)
        self._lt = datetime.datetime.fromtimestamp(0)

    @t.override
    @property
    def index_names(self) -> frozenset[str]:
        return frozenset(['time'])

    @t.override
    def score(self, index_name: str, record: tc.Record) -> tc.Score:
        if index_name != 'time':
            raise ValueError('Only the time index exists.')
        try:
            return record[self._ts_attr_name].timestamp()
        except KeyError:
            raise ValueError('Missing time attribute.')

    @t.override
    def primary_key(self, record: tc.Record) -> numbers.Real:
        try:
            return record[self._primary_key_name]
        except KeyError:
            raise ValueError('Missing primary key.')

    @t.override
    def storage_records_spec(
            self, spec: IndexSpec) -> tc.StorageRecordsSpec:
        return tc.StorageRecordsSpec(
            'time', [tc.Interval(spec.ge.timestamp(), spec.lt.timestamp())])

    @t.override
    def db_records_spec(
            self, spec: IndexSpec) -> tc.QueryArgsDbRecordsSpec:
        return tc.QueryArgsDbRecordsSpec(
            self._query_range_string, (spec.ge, spec.lt))

    @t.override
    def prepare_adjustment(self, spec: IndexSpec) -> Adjustment:
        expire_intervals = []
        if self._ge < spec.ge:
            expire_intervals.append(
                tc.Interval(self._ge.timestamp(), spec.ge.timestamp()))
        if self._lt > spec.lt:
            expire_intervals.append(
                tc.Interval(spec.lt.timestamp(), self._lt.timestamp()))
        if expire_intervals:
            expire_spec = tc.StorageRecordsSpec('time', expire_intervals)
        else:
            expire_spec = None
        load_spec = self.db_records_spec(spec)
        return self.Adjustment(expire_spec, load_spec, spec.ge, spec.lt)

    @t.override
    def commit_adjustment(self, adjustment: Adjustment) -> None:
        self._ge = adjustment.ge
        self._lt = adjustment.lt

    @t.override
    def covers(self, spec: IndexSpec) -> bool:
        return self._ge <= spec.ge and self._lt >= spec.lt


# This subclass of LocalStorageTable is only here to distinguish records loaded
# from storage (simple dicts) from ones loaded from the DB (asyncpg.Records)
# for the demonstration.
class LocalStorageTable(tcl.LocalStorageTable):
    async def get_records(
            self, records_spec: tc.StorageRecordsSpec) -> tc.AsyncRecords:
        records = super().get_records(records_spec)
        try:
            async for record in records:
                yield dict(record)
        finally:
            await records.aclose()


if __name__ == '__main__':
    asyncio.run(main())
