# Copyright 2023 Marc Lehmann

# This file is part of tablecache.
#
# tablecache is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# tablecache is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with tablecache. If not, see <https://www.gnu.org/licenses/>.

import asyncio
import contextlib
import pathlib
import sys

sys.path.append(str(pathlib.Path(__file__).parent.parent))

import asyncpg

import tablecache as tc


async def main():
    base_query_string = '''
        SELECT uc.*, u.name AS user_name, c.name AS city_name
        FROM
            users u
            JOIN users_cities uc USING (user_id)
            JOIN cities c USING (city_id)'''
    query_some_string = f'{base_query_string} WHERE uc.user_id = ANY ($1)'
    postgres_pool = asyncpg.create_pool(
        min_size=0, max_size=1,
        dsn='postgres://postgres:@localhost:5432/postgres')
    redis_storage = tc.RedisStorage()
    db_table = tc.PostgresTable(
        postgres_pool, base_query_string, query_some_string)
    storage_table = tc.RedisTable(
        redis_storage,
        primary_key_name='user_id',
        encoders={
            'user_id': tc.encode_int_as_str,
            'user_name': tc.encode_str,
            'city_name': tc.encode_str,},
        decoders={
            'user_id': tc.decode_int_as_str,
            'user_name': tc.decode_str,
            'city_name': tc.decode_str,},
    )
    async with contextlib.AsyncExitStack() as stack:
        await stack.enter_async_context(redis_storage)
        await stack.enter_async_context(postgres_pool)
        await setup_example_db(postgres_pool)
        table = tc.CachedTable(db_table, storage_table)
        await table.load()
        print(await table.get(1))  # Prints user 1 information from Redis.


async def setup_example_db(pool):
    await pool.execute(
        '''
        DROP SCHEMA public CASCADE;
        CREATE SCHEMA public;
        CREATE TABLE users (
            user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name text NOT NULL
        );
        CREATE TABLE cities (
            city_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name text NOT NULL
        );
        CREATE TABLE users_cities (
            user_id integer PRIMARY KEY REFERENCES users(user_id),
            city_id integer NOT NULL REFERENCES cities(city_id)
        );

        INSERT INTO users(user_id, name) VALUES(1, 'User 1');
        WITH c AS (INSERT INTO cities(name) VALUES('City 1') RETURNING city_id)
        INSERT INTO users_cities(user_id, city_id)
        SELECT 1, c.city_id FROM c;

        INSERT INTO users(user_id, name) VALUES(2, 'User 2');
        WITH c AS (INSERT INTO cities(name) VALUES('City 2') RETURNING city_id)
        INSERT INTO users_cities(user_id, city_id)
        SELECT 2, c.city_id FROM c;''')


if __name__ == '__main__':
    asyncio.run(main())
