name: test-tag-and-publish

on:
  push:
    branches-ignore:
      - "stash/**"
    tags-ignore:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker compose -f docker-compose.test.yml up --build --exit-code-from=test
      - name: Clean up
        if: ${{ always() }}
        run: docker compose -f docker-compose.test.yml down
  tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Determine version
        run: echo "VERSION=$(python setup.py --version)" >> "$GITHUB_ENV"
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION }}
          tag_prefix: ""
  publish-pypi:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: tag
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install build
        run: python -m pip install build
      - name: Build
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
